#include <stdio.h>
#include <stdlib.h>

#include "trie.h"
#include "scanner.h"

#define MAX_WORD_LEN 255

/* yylex() -> function used to retrieve the next token
   yytext  -> lexeme associated with the most recently scanned token */
extern int yylex(void);
extern char* yytext;

int main(int argc, char **argv)
{
    if (argc != 2) { /* Prefix length requirement is on the command line. */
        fprintf(stderr, "usage: %s PREFIX_LEN\n", argv[0]);
        return 1;
    }

    int prefix_len = atoi(argv[1]); /* No error checking here... */

    /* We construct a prefix tree or trie containing the characters of all
       IDENTIFIER lexemes. We use a scanner/lexer generated by flex for
       the C language to do the actual token identification. */
    struct Trie *root = init_trie(false);
    int token = yylex();
    while (token) {
        if (IDENTIFIER == token)
            addword(root, yytext);

        token = yylex();
    }

    /* The children of root represent the starting character of every variable
       name in the program. For each child, we run a common prefix search.
       If the search finds two or more words with a common prefix of at least
       prefix_len characters and who differ somewhere after, we output that
       group of words. */
    char word[MAX_WORD_LEN] = {0};
    for (int i = 0; i < ASCII_CHARS; ++i) {
        if (root->children[i]) {
            common_prefixes(root->children[i],
                            prefix_len - 1,
                            (char)i,
                            word,
                            0);
        }
    }
    free_trie(root);

    return 0;
}
